name: local_notifications
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

dependencies:
  # A cross platform plugin for displaying and scheduling local notifications for Flutter applications with the ability to customise for each platform.
  flutter_local_notifications: ^14.0.1

  # Time zone database and time zone aware DateTime.
  timezone: ^0.9.2

dev_dependencies:
  test: ^1.21.0
  very_good_analysis: ^4.0.0+1
