image: docker.miezhaus/studipadawan_flutter_arm64

variables:
  TARGET_BRANCH: "main"

stages:
  - Debug
  - Build

debug:
  stage: Debug
  script:
    - ls /home/developer/flutter/bin/cache/artifacts/engine/android-x64-release/linux-arm64/

build-apk:
  stage: Build
  script:
    - echo -n "$KEYSTORE" | base64 --decode > android/app/upload-keystore.jks
    - echo "keyPassword=$STORE_PASSWORD > android/key.properties"
    - echo "storePassword=$STORE_PASSWORD > android/key.properties"
    - echo "keyAlias=upload > android/key.properties"
    - echo "storeFile=upload-keystore.jks > android/key.properties"
    - flutter build apk
