image: docker.miezhaus/studipadawan_flutter_arm64

variables:
  TARGET_BRANCH: "main"

stages:
  - RepositoryTests

repository-tests:
  stage: RepositoryTests
  script: cd ./scripts && bash ./run_tests.sh
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $TARGET_BRANCH'
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $TARGET_BRANCH'
