image: aljoscha992/studipadawan_flutter_amd64:latest

variables:
  TARGET_BRANCH: "main"

stages:
  - UnitTests

unit-tests:
  stage: UnitTests
  script:
    - flutter test test
    - cd packages
    - |
      for dir in */; do
        if [ -f "$dir/pubspec.yaml" ] && grep -q "flutter_test" "$dir/pubspec.yaml"; then
          echo "Test $dir"
          cd "$dir"
          flutter pub get
          flutter test test
          cd ..
        fi
      done
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $TARGET_BRANCH'
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $TARGET_BRANCH'