image: aljoscha992/studipadawan_flutter_amd64:latest

variables:
  TARGET_BRANCH: "main"

stages:
  - Build
  - Release

build-apk:
  stage: Build
  script:
    - echo "Running build"
    - echo -n "$KEYSTORE" | base64 --decode > android/app/upload-keystore.jks
    - echo "keyPassword=$STORE_PASSWORD" >> android/key.properties
    - echo -e "storePassword=$STORE_PASSWORD" >> android/key.properties
    - echo -e "keyAlias=upload" >> android/key.properties
    - echo -e "storeFile=upload-keystore.jks" >> android/key.properties
    - export fhome=$(pwd)
    - cd packages/studip_api_client
    - dart run build_runner build
    - cd $fhome
    - flutter build apk --release
  artifacts:
    paths:
      - build/app/outputs/apk/release

release:
  stage: Release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: build-apk
      artifacts: true
  script:
    - echo "Running release"
  release:
    name: "$CI_COMMIT_MESSAGE"
    tag_name: "$CI_COMMIT_SHORT_SHA"
    description: "$CI_COMMIT_MESSAGE"

