image: aljoscha992/studipadawan_flutter_amd64:latest

variables:
  TARGET_BRANCH: "main"

stages:
  - Build

build-apk:
  stage: Build
  script:
    - echo -n "$KEYSTORE" | base64 --decode > android/app/upload-keystore.jks
    - echo "keyPassword=$STORE_PASSWORD" >> android/key.properties
    - echo -e "storePassword=$STORE_PASSWORD" >> android/key.properties
    - echo -e "keyAlias=upload" >> android/key.properties
    - echo -e "storeFile=upload-keystore.jks" >> android/key.properties
    - flutter build apk
