image: aljoscha992/studipadawan_flutter_amd64:latest

variables:
  TARGET_BRANCH: "main"

stages:
  - UnitTests

unit-tests:
  stage: UnitTests
  script:
    - |
      flutter pub get
      cd packages/studip_api_client
      dart run build_runner build
      cd ../..

      flutter test test
      cd packages

      for dir in */; do
        if [ -f "$dir/pubspec.yaml" ] && grep -q "flutter_test" "$dir/pubspec.yaml"; then
          echo "Test $dir"
          cd "$dir"
          flutter test test
          cd ..
        fi
      done
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $TARGET_BRANCH'
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $TARGET_BRANCH'

build-apk:
  stage: Build
  script:
    - echo -n "$KEYSTORE" | base64 --decode > android/app/upload-keystore.jks
    - echo "keyPassword=$STORE_PASSWORD > android/key.properties"
    - echo "storePassword=$STORE_PASSWORD > android/key.properties"
    - echo "keyAlias=studipadawan > android/key.properties"
    - echo "storeFile=upload-keystore.jks > android/key.properties"
    - flutter build apk
  artifacts:
    paths:
      - build/app/outputs/apk/release/StudIPadawan-1.0.0.apk