name: courses_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  intl: ^0.18.0
  studip_api_client:
    path: ../studip_api_client

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  very_good_analysis: ^4.0.0+1
