name: courses_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  studip_api_client:
    path: ../studip_api_client
  intl: ^0.18.0

dev_dependencies:
  lints: ^1.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  build_runner: ^2.3.3
