name: authentication_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  logger: ^1.3.0

  studip_api_client:
    path: ../studip_api_client

dev_dependencies:
  test: ^1.16.0
  very_good_analysis: ^4.0.0+1
