name: authentication_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  logger: ^1.3.0
  equatable: ^2.0.5
  studip_api_client:
    path: ../studip_api_client

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
