name: authentication_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  token_storage:
    path: ../token_storage

  oauth2_client: ^3.2.1
  http: ^0.13.5
  equatable: ^2.0.5
  jwt_decode: ^0.3.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
