include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    omit_local_variable_types: false
    public_member_api_docs: false
    always_put_required_named_parameters_first: false
    lines_longer_than_80_chars: false
