name: app_ui
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Simplifying the use of both Material and Cupertino widgets with a single widget
  flutter_platform_widgets: ^3.3.4

dev_dependencies:
  very_good_analysis: ^4.0.0+1
