name: messages_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  intl: ^0.18.0
  studip_api_client:
    path: ../studip_api_client
  timeago: ^3.4.0

dev_dependencies:
  test: ^1.21.0
  very_good_analysis: ^4.0.0+1
